apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-router
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/rule-type: PathPrefixStrip
spec:
  rules:
    - http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: ui-cluster-ip
              port:
                number: 80
        - path: /lighting
          pathType: Prefix
          backend:
            service:
              name: lighting-service-cluster-ip
              port:
                number: 8000
        - path: /devices
          pathType: Prefix
          backend:
            service:
              name: device-manager-service-cluster-ip
              port:
                number: 8000
