name: Docker Image CI

on:
  push:
    branches:
    - master
    - feature/*
    - bug/*
    
  pull_request:
    branches: 
    - master 

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    -
      name: Checkout
      uses: actions/checkout@v3
    - 
      name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
      name: Build and push Lighting Service
      run: |
        cd Service.Lighting
        docker compose build
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/lighting-service:latest
        
