name: Julian Docker CI

on:
  push:
    branches:
      - master
      - feature/julian/*
      - bug/julian/*

  pull_request:
    branches:
      - master

jobs:
  lighting_service:
    name: Lighting Service

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.JULIAN_DOCKER_HUB_USERNAME }}
          password: ${{ secrets.JULIAN_DOCKER_HUB_TOKEN }}
      - name: Build and push Lighting Service
        run: |
          cd Service.Lighting
          docker buildx build --platform linux/arm64 --tag ${{ secrets.JULIAN_DOCKER_HUB_USERNAME }}/iot-control-center:lighting-service --push .

  device_manager_service:
    name: Device Manager Service

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.JULIAN_DOCKER_HUB_USERNAME }}
          password: ${{ secrets.JULIAN_DOCKER_HUB_TOKEN }}
      - name: Build and push Device Manager Service
        run: |
          cd Service.DeviceManager
          docker buildx build --platform linux/arm64 --tag ${{ secrets.JULIAN_DOCKER_HUB_USERNAME }}/iot-control-center:device-manager-service --push .
  ui:
    name: UI

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.JULIAN_DOCKER_HUB_USERNAME }}
          password: ${{ secrets.JULIAN_DOCKER_HUB_TOKEN }}
      - name: Build and push Ui
        run: |
          cd Ui
          docker buildx build --platform linux/arm64 --tag ${{ secrets.JULIAN_DOCKER_HUB_USERNAME }}/iot-control-center:ui --push .

  kasa_bulb_controller:
    name: Kasa Bulb Controller

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.JULIAN_DOCKER_HUB_USERNAME }}
          password: ${{ secrets.JULIAN_DOCKER_HUB_TOKEN }}
      - name: Build and push Kasa Bulb Controller
        run: |
          cd Controller.KasaBulb
          docker buildx build --platform linux/arm64 --tag ${{ secrets.JULIAN_DOCKER_HUB_USERNAME }}/iot-control-center:kasa-bulb-controller --push .

  kasa_led_strip_controller:
    name: Kasa LED Strip Controller

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.JULIAN_DOCKER_HUB_USERNAME }}
          password: ${{ secrets.JULIAN_DOCKER_HUB_TOKEN }}
      - name: Build and push Kasa LED Strip Controller
        run: |
          cd Controller.KasaLedStrip
          docker buildx build --platform linux/arm64 --tag ${{ secrets.JULIAN_DOCKER_HUB_USERNAME }}/iot-control-center:kasa-led-strip-controller --push .
